{
 "title": "Fuzzing data with node data",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Fuzzer afl info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "corpus found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "fuzzing{type=\"corpus_found\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "exec/s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuzzing{type=\"execs_per_sec\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "fuzzing instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(banner) (fuzzing))",
     "legendFormat": "fuzzer instances"
    }
   ]
  },
  {
   "title": "crashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "fuzzing{type=\"saved_crashes\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "pending favs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "fuzzing{type=\"pending_favs\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "pending total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "fuzzing{type=\"pending_total\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "edges found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "fuzzing{type=\"edges_found\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "cycle done",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "fuzzing{type=\"cycle_done\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "cycle wo find",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 9 },
   "targets": [
    {
     "expr": "fuzzing{type=\"cycles_wo_finds\"}",
     "legendFormat": "{{banner}}"
    }
   ]
  },
  {
   "title": "Resource Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "All Node Overview [Job: $job, Total: $total]",
     "type": "table-old",
     "description": "Partition utilization, disk read, disk write, download bandwidth, upload bandwidth, if there are multiple network cards or multiple partitions, it is the value of the network card or partition with the highest utilization rate collected.\n\nCurrEstab: The number of TCP connections whose current status is ESTABLISHED or CLOSE-WAIT.",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
       "legendFormat": "主机名"
      },
      {
       "expr": "sum(time() - node_boot_time_seconds{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})by(instance)",
       "legendFormat": "运行时间"
      },
      {
       "expr": "node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
       "legendFormat": "总内存"
      },
      {
       "expr": "count(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode='system'}) by (instance)",
       "legendFormat": "总核数"
      },
      {
       "expr": "node_load5{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}",
       "legendFormat": "5分钟负载"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
       "legendFormat": "CPU使用率"
      },
      {
       "expr": "(node_memory_Buffers_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}+\nnode_memory_Cached_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}) / node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} * 100",
       "legendFormat": "内存使用率"
      },
      {
       "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
       "legendFormat": "分区使用率"
      },
      {
       "expr": "max(rate(node_disk_read_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])) by (instance)",
       "legendFormat": "最大读取"
      },
      {
       "expr": "max(rate(node_disk_written_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])) by (instance)",
       "legendFormat": "最大写入"
      },
      {
       "expr": "node_netstat_Tcp_CurrEstab{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
       "legendFormat": "连接数"
      },
      {
       "expr": "node_sockstat_TCP_tw{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
       "legendFormat": "TIME_WAIT"
      },
      {
       "expr": "max(rate(node_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])*8) by (instance)",
       "legendFormat": "下载带宽"
      },
      {
       "expr": "max(rate(node_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])*8) by (instance)",
       "legendFormat": "上传带宽"
      }
     ]
    },
    {
     "title": "$job：Overall total 5m load & average CPU used%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Total 5m load" }
     ],
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\", mode='system'})",
       "legendFormat": "CPU Cores"
      },
      {
       "expr": "sum(node_load5{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})",
       "legendFormat": "Total 5m load"
      },
      {
       "expr": "avg(1 - avg(rate(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
       "legendFormat": "Overall average used%"
      }
     ]
    },
    {
     "title": "$job：Overall total memory & average memory used%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "bytes", "label": "Total" }
     ],
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})",
       "legendFormat": "Total Used"
      },
      {
       "expr": "(sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}) / sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))*100",
       "legendFormat": "Overall Average Used%"
      }
     ]
    },
    {
     "title": "$job：Overall total disk & average disk used%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "bytes", "label": "Total" }
     ],
     "targets": [
      {
       "expr": "sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))",
       "legendFormat": "Total Used"
      },
      {
       "expr": "(sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))) *100/(sum(avg(node_filesystem_avail_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))+(sum(avg(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance)) - sum(avg(node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"xfs|ext.*\"})by(device,instance))))",
       "legendFormat": "Overall Average Used%"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 3, "x": 2, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
       "legendFormat": "CPU Busy"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used RAM Memory"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
       "legendFormat": "Used Max Mount($maxmount)"
      },
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
       "legendFormat": "Used SWAP"
      }
     ]
    },
    {
     "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
     "type": "table-old",
     "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
     "gridPos": { "h": 8, "w": 10, "x": 5, "y": 27 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
       "legendFormat": "总量"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
      }
     ]
    },
    {
     "title": "CPU% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 1, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total filefd",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_filefd_maximum{instance=~\"$node\"})"
      }
     ]
    },
    {
     "title": "CPU iowait",
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) * 100"
      }
     ]
    },
    {
     "title": "Free inodes:$maxmount ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 1, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_filesystem_files_free{instance=~\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext.?|xfs\"})"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{instance=~\"$node\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{instance=~\"$node\"}",
       "legendFormat": "15m"
      },
      {
       "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
       "legendFormat": "CPU cores"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
       "legendFormat": "Used%"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - (node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"} + node_memory_MemFree_bytes{instance=~\"$node\"})",
       "legendFormat": "Used(total-cached-buffers-free)"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node\"}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"} - node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "Used(total-avail)"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"}",
       "legendFormat": "Avvilable"
      }
     ]
    },
    {
     "title": "Disk Space Used% Basic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk IOps Completed（IOPS）",
     "type": "graph",
     "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Writes completed"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Written bytes"
      }
     ]
    },
    {
     "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
     "type": "graph",
     "description": "Time spent on each read/write operation",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "s", "label": "Time read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Read time"
      },
      {
       "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_Write time"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "graph",
     "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "{{device}}_ IO time"
      }
     ]
    },
    {
     "title": "Open  File Descriptor(left)/Context switches(right)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short", "label": "used filefd" }
     ],
     "targets": [
      {
       "expr": "node_filefd_allocated{instance=~\"$node\"}",
       "legendFormat": "used filefd"
      },
      {
       "expr": "rate(node_context_switches_total{instance=~\"$node\"}[$interval])",
       "legendFormat": "switches"
      }
     ]
    },
    {
     "title": "Allocated Threads and Processes",
     "type": "graph",
     "description": "Equivalent to: cat /proc/sys/kernel/pid_max or cat /proc/sys/kernel/threads-max, It is often used to analyze unlimited fork threads caused by user program bugs. For example, the JVM has been creating threads or thread pools without releasing them.  Note: the upper limit of fork thread is controlled by pid_max and threads-max impact. When the upper limit is reached, any client trying to connect to any protocol listening service (TCP or SSH or HTTP) cannot respond, and an error is reported, such as fork: cannot allocate memory. For the principle, please refer to the kernel source code: https://github.com/torvalds/linux/blob/v3.10/include/linux/thread_info.h, See experience with tears in a production env: https://blogs.wl4g.com/archives/2019",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_processes_threads{job=\"node\",instance=~\"$node\"}",
       "legendFormat": "allocated threads"
      },
      {
       "expr": "node_processes_pids{job=\"node\",instance=~\"$node\"}",
       "legendFormat": "allocated processes"
      },
      {
       "expr": "node_processes_max_threads{job=\"node\",instance=~\"$node\"} / 1000",
       "legendFormat": "max threads(K)"
      },
      {
       "expr": "node_processes_max_processes{job=\"node\",instance=~\"$node\"} / 1000",
       "legendFormat": "max processes(K)"
      }
     ]
    }
   ]
  }
 ]
}